server:
  port: 9000
#zuul:
#  routes:
#    demo:
#      url: http://localhost:9090/
spring:
  application:
    name: zuul-gateway
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    ServiceB:
      path: /demo/**